# Generated by Django 5.1 on 2025-09-18 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adult",
            name="cessation",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")],
                default="no",
                max_length=3,
                verbose_name="Smoking Cessations",
            ),
        ),
        migrations.AlterField(
            model_name="adult",
            name="smoking",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")],
                default="no",
                max_length=3,
                verbose_name="Smoking",
            ),
        ),
    ]
