# Generated by Django 5.1 on 2025-09-20 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adult",
            name="allergy",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")],
                default="no",
                max_length=3,
                verbose_name="Allergy",
            ),
        ),
        migrations.AlterField(
            model_name="adult",
            name="contraception",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")],
                default="no",
                max_length=3,
                verbose_name="Contraception",
            ),
        ),
        migrations.AlterField(
            model_name="adult",
            name="jaundice",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")],
                default="no",
                max_length=3,
                verbose_name="Jaundice",
            ),
        ),
        migrations.AlterField(
            model_name="adult",
            name="pallor",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")],
                default="no",
                max_length=3,
                verbose_name="Pallor",
            ),
        ),
    ]
