# Generated by Django 5.1 on 2025-09-20 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0002_alter_adult_allergy_alter_adult_contraception_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adult",
            name="age",
        ),
        migrations.AddField(
            model_name="patient",
            name="age",
            field=models.IntegerField(default=0),
        ),
    ]
