# Generated by Django 5.0.8 on 2025-09-18 10:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClinicModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Clinic Name")),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Clinic Descriptions"
                    ),
                ),
            ],
            options={
                "verbose_name": "Clinic",
                "verbose_name_plural": "Clinics",
            },
        ),
        migrations.CreateModel(
            name="CyanosisModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_on", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Cyanosis",
                "verbose_name_plural": "Cyanoses",
            },
        ),
        migrations.CreateModel(
            name="DrugModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_on", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Drug",
                "verbose_name_plural": "Drugs",
            },
        ),
        migrations.CreateModel(
            name="FamilyHistoryModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_on", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="MedicalModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_on", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="SymptomModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Symptom Name")),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Symptom Description"
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_on", models.DateTimeField(auto_now=True, null=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="others.clinicmodel",
                        verbose_name="Clinic",
                    ),
                ),
            ],
            options={
                "verbose_name": "Symptom",
                "verbose_name_plural": "Symptoms",
                "unique_together": {("name", "clinic")},
            },
        ),
    ]
